### PR TITLE
Add correct command

### PR DESCRIPTION
**Pull request by Rafi594**

### CODE REVIEW

**Comment by ldidry** [comment]
It may need a `chown` after the `cp` (don't bother about owner/group/permissions is why I did a `cat`).

**Comment by Rafi594** [comment]
sudo cat return permission denied
https://paste.yunohost.org/enogirewos.sm
https://github.com/YunoHost-Apps/minetest_ynh/blob/master/scripts/install#L90

**Comment by Rafi594** [comment]
Is minetest had a dedicated user

**Comment by ldidry** [comment]
Replace `sudo cat $file1 > $file2` by `cat $file1 | sudo tee $file2 >/dev/null`. And yes, the user is `Debian-minetest`.

**Pull request merged**
