### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by supermamie** [comment]
Capture d’écran du 2024-01-08 16-22-11

Quick test on my server, it seems I have a problem somewhere.

Please note that I use a different game : mineclonia.

I have a lot of messages, about entities not existing : 
```
ERROR[Server]: LuaEntity name "mcl_signs:text" not defined
```

**Comment by ericgaspar** [comment]
> Please note that I use a different game : mineclonia.

Don't we have to install an extra something for mineclonia?

Did you try with `minetest_game` or `capturetheflag` game?

**Comment by supermamie** [comment]
OOps, I forgot to comment here.
A fresh install works perfectly.

I'll add another PR to add mineclonia, it could be ignored, I'll maintain my own fork just for my configuration :p

**Pull request merged**
